### ISSUE TITLE
XML Issues( Path.isConvex is not supported)

### ISSUE THREAD

**Issue by ayush18verma** [developer-shivam/Crescento#1]
If you use leftradius,rightradius and so on in your coding of this library , please change into only radius with same value.

Because this thing issue an error in xml thats doesn't show any preview. 
Error is :- 
The graphics preview in the layout editor may not be accurate: 
- Path.isConvex is not supported

Thank you.

**Comment by developer-shivam** [comment]
Its not the problem with left radius or right radius. Its just studio is unable to populate the view which is now fixed in latest update.
