### ISSUE TITLE
attribute:curvature is not work properly

### ISSUE THREAD

**Issue by Khyati-Fatania** [developer-shivam/Crescento#2]

**Comment by developer-shivam** [comment]
Can you please elaborate?

**Comment by mreil617** [comment]
I can add some input here.

When you adjust the curvature property the image should not get smaller in vertical size. Just curved mask should change. An example of this can be achieved by adding a view with the following properties:

<developer.shivam.library.CrescentoImageView
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:scaleType="centerCrop"
                app:gravity="top"/>

**Comment by developer-shivam** [comment]
I have resolved this issue, so closing now!
