### ISSUE TITLE
Attribute "tintMode" already defined with incompatible format.

### ISSUE THREAD

**Issue by Aednlaxer** [developer-shivam/Crescento#5]
When using with Support library 25.4.0 Crescento's `app:tintMode` attribute clashes with `tintMode` attribute from the Support Libraries (ImageView, AppCompatImageView).

Build error:
```
Attribute "tintMode" already defined with incompatible format.
Original attribute defined here.
```

How to reproduce: create new project with Support Libraries 25.4.0 and Crescento library. Try to build and get the error.

**Comment by vlanfranchi-ecocea** [comment]
Same problem here

**Comment by Aednlaxer** [comment]
The library is not compatible with Support Libraries 25.4.0. The problem seems to be in the [attrs.xml](https://github.com/developer-shivam/Crescento/blob/master/crescento/src/main/res/values/attrs.xml#L13):
```
<attr name="tintMode" format="integer">
  <flag name="automatic" value="0" />
  <flag name="manual" value="1" />
</attr>
```

`tintMode` attribute declared in Support Library has different format. This can be fixed by renaming library's `tintMode` to something like `crescentoTintMode`. Ping @developer-shivam

**Comment by frapeti** [comment]
+1

**Comment by developer-shivam** [comment]
Fixed this issue, so closing it!
