### ISSUE TITLE
Failed to resolve: com.github.developer-shivam:crescento:1.2.0

### ISSUE THREAD

**Issue by SIMMORSAL** [developer-shivam/Crescento#6]
Hi, I'm trying to add version 1.2.0 to my project, but i get this error. version 1.1.0 works fine though.

**Comment by developer-shivam** [comment]
Please provide the error log.

**Comment by SIMMORSAL** [comment]
The title is all i get!
![untitled-1](https://user-images.githubusercontent.com/24822099/27984286-5384e658-63e7-11e7-8445-e96b989214b9.png)

**Comment by developer-shivam** [comment]
Fixed! Please try again.

**Comment by SIMMORSAL** [comment]
Unfortunately I still get the same error.

**Comment by developer-shivam** [comment]
Copy as it is - compile 'com.github.developer-shivam:Crescento:1.2.0'

**Comment by SIMMORSAL** [comment]
Awesome, worked. thanks

**Comment by agustinsivoplas** [comment]
@developer-shivam in the home page the dependency is in lowercase instead uppercase
<img width="920" alt="screen shot 2017-07-21 at 10 22 21" src="https://user-images.githubusercontent.com/1648539/28465319-ad2ca72e-6dfe-11e7-8b8a-c328725d72ef.png">

**Comment by amank22** [comment]
@developer-shivam please update the readme with the correction @agustinsivoplas pointed out. Will help others.

**Comment by developer-shivam** [comment]
Done!
