### ISSUE TITLE
How to change the background color of the Crescento Container?

### ISSUE THREAD

**Issue by anitaa1990** [developer-shivam/Crescento#8]
I do not require an imageview. I just need to have a curved layout with a different background color. But the background does not seem to change. It is always White.

**Comment by anitaa1990** [comment]
Never mind! got it working by adding an imageview inside the container  & setting the background to that imageView:

`<developer.shivam.library.CrescentoContainer
        android:id="@+id/crescentoContainer"
        android:layout_width="match_parent"
        android:layout_height="280dp"
        android:elevation="1dp"
        android:scaleType="centerCrop"
        app:curvature="50dp"
        app:crescentoTintAlpha="255"
        app:backgroundColor="@color/colorPrimary"
        app:crescentoTintColor="@color/colorPrimary"
        app:gradientStartColor="@color/colorPrimary"
        app:gradientEndColor="@color/colorPrimary">

        <ImageView
            android:background="@color/colorPrimary"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />


    </developer.shivam.library.CrescentoContainer>`

**Comment by Arunkrishna008** [comment]
now i got an  error like Error:(11) error: attribute 'relo.pc.primalcodes.myapplication:backgroundColor' not found.
                this is my layout



<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@android:color/white"
    tools:targetApi="lollipop"
    xmlns:attribute="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical">
    <developer.shivam.library.CrescentoContainer
        android:id="@+id/crescentoContainer"
        android:layout_width="match_parent"
        android:layout_height="280dp"
        android:elevation="1dp"
        android:scaleType="centerCrop"
        app:curvature="50dp"
        app:crescentoTintAlpha="255"
        app:backgroundColor="@color/colorPrimary"
        app:crescentoTintColor="@color/colorPrimary"
        app:gradientStartColor="@color/colorPrimary"
        app:gradientEndColor="@color/colorPrimary">

        <ImageView
            android:background="@color/colorPrimary"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />


    </developer.shivam.library.CrescentoContainer>

      </LinearLayout>
